# Kadai Store API v1.0.0
# 基本的な設定

# デフォルトとして、推奨値を入れてあります。ご参考にしてください。

# MS Teamsから課題情報を取得する、時間の間隔(分)をここで指定します。
# 1 以上の整数を入れてください。
update_duration: 5

# MS Teamsから課題情報を取得しない、時(hour)があれば、ここで指定します。(複数指定可)
# 0 から 23 の中の整数を入れてください。指定がない場合は [] にしてください。
update_offtimes: []

# 1つのトークンが、 get_limit_duration で指定する期間内に、このAPI(/get)にGETできる回数をここで指定します。(レート制限)
# 1 以上の整数もしくは -1 を入れてください。指定しない場合は -1 を入れてください。
get_limit: 60

# get_limit の期間(分)をここで指定します。
# 1 以上の整数もしくは -1 を入れてください。get_limit で指定していない場合は -1 を入れてください。
get_limit_duration: 10

# 一時的なデータを保管するディレクトリをここで指定できます。
# 指定がない場合は、OSにて設定されている一時フォルダを使用します。
tmp-dir:

# UTC(協定世界時)以外に扱うタイムゾーンをここで指定します。
# 利用可能なタイムゾーンは https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List の
# TZ database name をご覧ください。
timezones:
  - Asia/Tokyo
  - Asia/Ulaanbaatar
  - Asia/Bangkok

# 取得する課題が格納されているチーム名と、教科名、教科IDをここで指定します。
# 同じ教科の複数のチームがある場合は、教科名と教科IDを同じにし、チーム名を全てお書きください。
#   チーム名: MS Teamsで確認することができる、チーム名
#   教科名:   シラバスに記載されている教科名 (任意の名前)
#   ID:      URLクエリパラメータで、教科を指定するためのID (任意の名前)
# 配列の0番目にチーム名、1番目に教科名、2番目にIDを入れてください。
subjects:
  - ["[024]J2HR2020", "HR", "hr"]
  - ["[024] 2020 J2A  国語", "国語２", "japanese2"]
  - ["[024]2年歴史2(2020)", "歴史２", "history2"]
  - ["[024](5/8まで,2年)基礎数学4(2020)", "基礎数学４", "math4"]
  - ["[024]J2_基礎数学4（2020）", "基礎数学４", "math4"]
  - ["[024]J2A_微分積分1（2020）", "微分積分１", "calculus1"]
  - ["[024](5/8まで,2年)代数幾何1(2020)", "代数・幾何１", "geometry1"]
  - ["J2", "代数・幾何１", "geometry1"]
  - ["J2A", "代数・幾何１", "geometry1"]
  - ["[024]物理2-2020", "物理２", "physics2"]
  - ["[024]理科総合-2020後期", "理科総合", "science"]
  - ["[024]J2A保健体育22020", "保健体育2", "hpe2"]
  - ["【024】English Communication3　J2AB　2020", "English Communication３", "ec3"]
  - ["【024】J2A EC4", "English Communication４", "ec4"]
  - ["[024]English Expression 2 (EE2)", "English Expression２", "ee2"]
  - ["[024]1年2年一般基礎教育1・2(2020)", "一般基礎教育２", "education2"]
  - ["[024]2年一般基礎教育２(2020)", "一般基礎教育２", "education2"]
  - ["[024]J2情報工学2 2020", "情報工学2", "computer2"]
  - ["[024] J2電気電子工学2020", "電気電子工学", "electronic"]
  - ["[024]J2機械加工基礎2020", "機械加工基礎", "mechanics"]
  - ["[024]J2情報工学1・PBL2(2020)", "PBL2", "pbl2"]

# 当APIにアクセスを許可するトークンをここで指定します。(任意の文字列)
# ここで定めたものを、API利用者にお伝えください。
allow-tokens:
  - anataga-kimeta
  - token-wo
  - kokoni
  - irerunja!