runtime: nodejs14
# 1024MBメモリを使用
instance_class: B4
basic_scaling:
  max_instances: 1

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

includes:
 - environ.yaml